Added guidelines for asking for help
nextcord/previous pull request #34
Opened 2021-11-11 04:10 UTC by squigjess

- When a new help menu is created with `=help_menu`, a message containing guidelines on how to appropriately and effectively ask for help is included as well as the buttons.
- The guidelines are placed above the buttons, forcing the user to read (or at least scroll past) the guidelines before opening a new help thread.
- Compartmentalised the contents of the help message into a .txt file to allow for easier editing in the future if any guideline changes are needed down the line.
- Given that Discord has a 2000-character limit on messages sent by users _and_ bots, `split_txtfile()` will split the text file into adequately-sized chunks that can then be sent in multiple messages, one after the other.

2021-11-11 07:20 UTC, ooliver1 approved these changes

2021-11-11 11:54 UTC, squigjess commented
Need to make some changes, please don't merge yet.

2021-11-12 10:51 UTC, Skelmis reviewed
Lgtm once you change it over to embeds

2021-11-12 12:01 UTC, VincentRPS approved these changes
lgtm

2021-11-12 13:01 UTC, squigjess commented
Added the following to the closing msgs for both the Close button and `=close` command.
![image](https://user-images.githubusercontent.com/701075/141471021-523eb53b-5766-4ff4-b6fb-3b59c451d814.png)

I'll make another PR later on to move the thread-closing code to a function once this has been merged.

2021-11-13 01:26 UTC, Skelmis requested changes

2021-11-13 01:26 UTC, Skelmis commented on cogs/help.py
> +                            description="If your question has not been answered or your issue not resolved, we suggest taking a look at [Python's Guide to Asking Good Questions](https://www.pythondis
Make this multi line, lets keep character line counts reasonable.

2021-11-13 01:26 UTC, Skelmis commented on cogs/help.py
> +                                description="If your question has not been answered or your issue not resolved, we suggest taking a look at [Python's Guide to Asking Good Questions](https://www.pytho
Make this multi line, lets keep character line counts reasonable.

2021-11-13 02:24 UTC, VincentRPS approved these changes
lgtm

2021-11-13 04:54 UTC, Skelmis approved these changes

2021-11-21 09:01 UTC, TAG-Epic requested changes
Imo the rules can be shortened a ton

2021-11-23 07:36 UTC, TAG-Epic approved these changes

2021-11-23 07:36 UTC, merged